<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'taxonomy-terms show');
$this->headLink()->appendStylesheet($this->assetUrl('css/site/taxonomy.css', 'Taxonomy'));
?>

<?php echo $this->pageTitle($taxonomyTerm->displayTitle()); ?>

<?php $this->trigger('view.show.before'); ?>

<div id="taxonomy-term-taxonomy" class="section">
    <h2><?php echo $translate('Taxonomy'); ?></h2>
    <?php echo $taxonomyTerm->taxonomy()->linkPretty(); ?>
</div>

<div id="taxonomy-term-metadata" class="section">
    <h2><?php echo $translate('Metadata'); ?></h2>
    <?php if ( $taxonomyTerm->resourceClass()): ?>
        <div class="meta-group">
            <h4><?php echo $translate('Class'); ?></h4>
            <div class="value"><?php echo $escape($taxonomyTerm->resourceClass()->label()); ?></div>
        </div>
    <?php endif; ?>
    <?php echo $taxonomyTerm->displayValues(); ?>
</div>

<?= $this->partial('taxonomy/site/taxonomy-term/linked-resources', ['taxonomyTerm' => $taxonomyTerm]) ?>

<?php $this->trigger('view.show.after'); ?>
