<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'taxonomy-terms show');
?>

<?php echo $this->pageTitle($taxonomyTerm->displayTitle()); ?>

<?php $this->trigger('view.show.before'); ?>

<div id="taxonomy-term-taxonomy" class="section">
    <h2><?php echo $translate('Taxonomy'); ?></h2>
    <?php echo $taxonomyTerm->taxonomy()->linkPretty(); ?>
</div>

<div id="taxonomy-term-metadata" class="section">
    <h2><?php echo $translate('Metadata'); ?></h2>
    <?php if ( $taxonomyTerm->resourceClass()): ?>
        <div class="meta-group">
            <h4><?php echo $translate('Class'); ?></h4>
            <div class="value"><?php echo $escape($taxonomyTerm->resourceClass()->label()); ?></div>
        </div>
    <?php endif; ?>
    <?php echo $taxonomyTerm->displayValues(); ?>
</div>

<div id="taxonomy-term-linked" class="section">
    <h2><?php echo $translate('Linked resources'); ?></h2>
    <?php
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $taxonomyTerm->displaySubjectValuesCompat(['page' => $page, 'perPage' => 25]);
    ?>
    <?php if ($subjectValues): ?>
        <p><?php echo $translate('The following resources link to this taxonomy term:'); ?></p>
        <?php echo $subjectValues; ?>
    <?php else: ?>
        <div class="no-resources">
            <p><?php echo $translate('No resources link to this taxonomy term.'); ?></p>
        </div>
    <?php endif; ?>
</div>

<?php $this->trigger('view.show.after'); ?>
