<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'taxonomy-terms browse browse-hierarchy');
?>

<?php echo $this->pageTitle($translate('Taxonomy terms'), 1, $translate($taxonomy->displayTitle())); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($translate('View as list'), $this->url('admin/taxonomy-term', [], ['query' => ['taxonomy_id' => $taxonomy->id()]]), ['class' => 'button']); ?>

    <?php if ($this->userIsAllowed('Taxonomy\Api\Adapter\TaxonomyTermAdapter', 'create')): ?>
        <?php echo $this->hyperlink($translate('Add new taxonomy term'), $this->url('admin/taxonomy-id', ['id' => $taxonomy->id(), 'action' => 'add-term']), ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php $this->trigger('view.browse-hierarchy.before'); ?>

<div class="taxonomy-term-tree" data-children-url="<?= $this->url('admin/taxonomy-term', ['action' => 'browse-jstree'], ['query' => ['taxonomy_id' => $taxonomy->id(), 'sort_by' => 'title', 'sort_order' => 'asc']]) ?>"></div>

<?php $this->trigger('view.browse-hierarchy.after'); ?>

<div id="sidebar" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>
