<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'add taxonomies');
?>

<?php echo $this->pageTitle($translate('New taxonomy'), 1, $translate('Taxonomies')); ?>
<?php $this->trigger('view.add.before'); ?>
<?php
echo $this->partial('taxonomy/admin/taxonomy/form.phtml', [
    'form' => $form,
    'taxonomy' => null,
    'sectionNavEvent' => 'view.add.section_nav',
    'action' => 'add',
]);
?>

<?php $this->trigger('view.add.after'); ?>
