<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$taxonomiesFound = count($taxonomies) > 0;
?>

<h3><?php echo $translate('Select taxonomy'); ?></h3>
<div class="search-nav">
    <div id="sidebar-resource-search" class="resource-search" data-search-url="<?php echo $escape($this->url(null, [], [], true)); ?>">
        <input type="text" name="search" value="<?php echo $escape($searchValue); ?>" id="resource-list-search">
        <button type="button" class="o-icon-search"><?php echo $translate('Search'); ?></button>
    </div>
    <?php if ($taxonomiesFound): ?>
        <?php echo $this->pagination('common/sidebar-pagination.phtml'); ?>
    <?php endif; ?>
</div>

<div class="taxonomies resource-list">
    <?php if ($taxonomiesFound): ?>
        <?php
        foreach ($taxonomies as $taxonomy): ?>
        <div class="resource taxonomy">
            <?php
            $content = sprintf(
                '%s<span class="resource-name">%s</span>',
                $this->thumbnail($taxonomy, 'square'),
                $escape($taxonomy->displayTitle())
            );
            echo $hyperlink->raw($content, '#', [
                'class' => 'sidebar-content select-resource resource-link',
                'data-sidebar-content-url' => $taxonomy->url('show-details'),
                'data-sidebar-selector' => '#resource-details',
            ]);
            ?>
        </div>
        <?php endforeach; ?>
    <?php else: ?>
        <span class="no-resources"><?php echo $translate('No taxonomies found.'); ?></span>
    <?php endif; ?>
</div>


