<div class="taxonomy-linked-resources__sort">
    <span><?= $this->translate('Sort by') ?></span>
    <select class="taxonomy-linked-resources__sort-select">
        <option value="dcterms:title asc"><?= $this->translate('Title (A-Z)') ?></option>
        <option value="dcterms:title desc"><?= $this->translate('Title (Z-A)') ?></option>
        <option value="dcterms:date asc"><?= $this->translate('Date (ascending)') ?></option>
        <option value="dcterms:date desc"><?= $this->translate('Date (descending)') ?></option>
    </select>
</div>
