<div class="taxonomy-linked-resources__sort">
    <span><?= $this->translate('Sort by') ?></span>
    <select class="taxonomy-linked-resources__sort-select">
        <option value="dcterms:title asc"><?= $this->translate('Title (asc)') ?></option>
        <option value="dcterms:title desc"><?= $this->translate('Title (desc)') ?></option>
        <option value="dcterms:date asc"><?= $this->translate('Date (asc)') ?></option>
        <option value="dcterms:date desc"><?= $this->translate('Date (desc)') ?></option>
    </select>
</div>
