<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<div class="resource-inputs">
    <span class="default"><?php echo $translate('No resource selected'); ?></span>
    <p class="selected-resource">
        <span class="o-title"></span>
        <input type="hidden" class="value to-require" data-value-key="value_resource_id">
    </p>

    <?php
    echo $this->hyperlink(sprintf($translate('Taxonomy terms: %s'), $taxonomy->displayTitle()), '#taxonomy-term-resource-select', [
        'class' => 'o-icon-taxonomy-terms button resource-select',
        'data-sidebar-content-url' => $this->url('admin/taxonomy-term', ['action' => 'sidebar-select'], ['query' => ['taxonomy_id' => $taxonomy->id(), 'sort_by' => 'title', 'sort_order' => 'asc']]),
    ]);
    ?>
</div>
