<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<div class="resource-inputs">
    <span class="default"><?php echo $translate('No resource selected'); ?></span>
    <p class="selected-resource">
        <span class="o-title"></span>
        <input type="hidden" class="value to-require" data-value-key="value_resource_id">
    </p>

    <?php
    echo $this->hyperlink($translate('Taxonomies'), '#taxonomy-resource-select', [
        'class' => 'o-icon-taxonomies button resource-select',
        'data-sidebar-content-url' => $this->url('admin/taxonomy', ['action' => 'sidebar-select'], false),
    ]);
    ?>
</div>
