<div class="input-body">
    <span class="default"><?php echo $this->translate('No resource selected'); ?></span>
    <p class="selected-resource">
        <span class="o-title taxonomy_terms"></span>
        <input type="hidden" class="value_resource_id" data-value-key="value_resource_id">
        <input type="hidden" class="display_title" data-value-key="display_title">
        <input type="hidden" class="url" data-value-key="url">
        <input type="hidden" class="thumbnail_url" data-value-key="thumbnail_url">
    </p>
    <?php echo $this->hyperlink($this->translate('Taxonomy terms'), '#', [
        'class' => 'o-icon-taxonomy-terms button value-annotation-resource-select',
        'data-sidebar-content-url' => $this->url('admin/taxonomy-term', ['action' => 'sidebar-select'], ['query' => ['taxonomy_id' => $taxonomy->id(), 'sort_by' => 'title', 'sort_order' => 'asc']], false),
    ]); ?>
</div>
